### ISSUE TITLE
Okada model version

### ISSUE THREAD

**Issue by OrionApplePie** [clawpack/seismic#15]
Which version of Okada model is implemented here, 1985 or 1992?:  https://github.com/clawpack/seismic/blob/962cbf6d541fe547cc2093ea1368a9752d5f9659/src/python/seismic/dtopotools_horiz_okada_and_1d.py#L1461

**Comment by rjleveque** [comment]
Like the 2D clawpack.geoclaw.dtopotools.Fault.create_dtopography function
<https://www.clawpack.org/okada.html>, this 1D version computes the surface
deformation following Okada 1985.  The 1992 paper extended the formulas to
internal deformation but we do not compute this.

 - Randy

**Comment by OrionApplePie** [comment]
Thanks.
